#!/usr/bin/env python3
"""
motion.json -> 獨立的 AS 程式。不需要 PC 連線,載進控制器就能跑。

用途是離線測試:手上還沒有治具、或是想先確認路徑對不對的時候,
把動作計畫直接烤成一支 AS 程式,用示教器執行。

正式運轉還是走 stream.py 即時串流 —— 那條路點位不受程式步數限制,
而且換一個字不用重新載入程式。

注意:產出的註解一律 ASCII。中文註解在 Kawasaki 的編輯器上會被編碼
轉換打壞,吃掉行尾換行,把下一行併進註解裡。踩過兩次。

用法:
  python motion2as.py motion.json -o test.as --name sugar_frame
"""
import argparse, json, os

HEAD = """.PROGRAM {name}()
; =====================================================================
; {title}
; Generated by motion2as.py from {src}
;
; {nmove} motions, {npt} positions, estimated {est} s
; Offsets are relative to "org", the centre of the drawing area.
; X range {xlo:+.1f} to {xhi:+.1f} mm, Y range {ylo:+.1f} to {yhi:+.1f} mm
;
; BEFORE RUNNING
;   1. org must be taught (run org_teach) or this will not move sensibly.
;   2. Set TOOL correctly.  With no nozzle fitted use TOOL 0 (flange),
;      otherwise the coordinates follow some other tool's TCP.
;   3. Turn the pendant speed override down to 20 percent for the first
;      run and keep a hand on the e-stop.
;   4. dryrun = 1 skips the valve signals.  Set it to 0 only when a
;      valve is actually wired to the output.
;
; ALL COMMENTS MUST STAY ASCII - see sugar_server.as header.
; =====================================================================

  dryrun = 1                 ; 1 = do not touch the valve output
  sig    = {sig}                  ; valve digital output number

  ACCURACY {acc:g} ALWAYS
"""

FOOT = """  PRINT "{name} done"
.END

.PROGRAM Comment___ () ; Comments for IDE. Do not use.
\t; @@@ PROJECT @@@
\t; @@@ PROJECTNAME @@@
\t; {name}
\t; @@@ HISTORY @@@
\t; @@@ INSPECTION @@@
\t; @@@ CONNECTION @@@
\t; 
\t; 
\t; 
\t; @@@ PROGRAM @@@
\t; 0:{name}:F
\t; @@@ TRANS @@@
\t; @@@ JOINTS @@@
\t; @@@ REALS @@@
\t; @@@ STRINGS @@@
\t; @@@ INTEGER @@@
\t; @@@ SIGNALS @@@
\t; @@@ TOOLS @@@
\t; @@@ BASE @@@
\t; @@@ FRAME @@@
\t; @@@ BOOL @@@
\t; @@@ DEFAULTS @@@
\t; BASE: NULL
\t; TOOL: NULL
.END
"""

def convert(d, name, title):
    mv = d["moves"]
    xs = [m["x"] for m in mv if "x" in m]
    ys = [m["y"] for m in mv if "y" in m]
    out = [HEAD.format(
        name=name, title=title, src=d.get("source", "?"),
        nmove=len(mv), npt=len(xs), est=d.get("est_seconds", "?"),
        xlo=min(xs), xhi=max(xs), ylo=min(ys), yhi=max(ys),
        sig=abs(next((m["n"] for m in mv if m["op"] == "sig"), 1)),
        acc=d.get("accuracy", 3))]

    lastv = None
    for i, m in enumerate(mv, 1):
        o = m["op"]
        if o in ("lmove", "jmove"):
            if m["v"] != lastv:
                out.append(f"  SPEED {m['v']:g} MM/S ALWAYS")
                lastv = m["v"]
            out.append(f"  POINT st = SHIFT(org BY {m['x']:.2f}, "
                       f"{m['y']:.2f}, {m['z']:g})")
            out.append(f"  {o.upper()} st")
        elif o == "ldepart":
            if m["v"] != lastv:
                out.append(f"  SPEED {m['v']:g} MM/S ALWAYS")
                lastv = m["v"]
            out.append(f"  LDEPART {m['d']:g}")
        elif o == "sig":
            out.append("  IF dryrun == 0 THEN")
            out.append(f"    SIGNAL {m['n']:g}")
            out.append("  END")
        elif o == "wait":
            out.append(f"  TWAIT {m['t']:g}")
        elif o == "brk":
            out.append("  BREAK")
        elif o == "end":
            pass
    out.append(FOOT.format(name=name))
    return "\n".join(out)

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("json", help="plan.py 的 motion.json")
    ap.add_argument("-o", "--out", default="test.as")
    ap.add_argument("--name", default="sugar_test2", help="AS 程式名,<=15 字元")
    ap.add_argument("--title", default="Offline path test", help="程式標題(ASCII)")
    v = ap.parse_args()

    if len(v.name) > 15:
        raise SystemExit("AS 的程式名上限 15 字元(手冊 3.4)")
    if not v.title.isascii():
        raise SystemExit("標題必須是 ASCII —— 中文註解會被編輯器打壞")

    d = json.load(open(v.json, encoding="utf-8"))
    txt = convert(d, v.name, v.title)
    if not txt.isascii():
        raise SystemExit("產出含非 ASCII 字元,請檢查")
    open(v.out, "w", encoding="ascii", newline="\r\n").write(txt)

    n = txt.count("\n") + 1
    print(f"{len(d['moves'])} 個動作 -> {n} 行 AS -> {v.out}")
    print(f"程式名 {v.name},載入後用示教器執行")
    print("提醒:先確認 org 已示教、TOOL 設對、速度倍率調低")

if __name__ == "__main__":
    main()
