.PROGRAM sugar_yi()
; =====================================================================
; Single character test: yi (one horizontal stroke)
; Generated by motion2as.py from y1.pts.json
;
; 34 motions, 25 positions, estimated 3.5 s
; Offsets are relative to "org", the centre of the drawing area.
; X range -78.0 to +78.0 mm, Y range -6.0 to +6.0 mm
;
; BEFORE RUNNING
;   1. org must be taught (run org_teach) or this will not move sensibly.
;   2. Set TOOL correctly.  With no nozzle fitted use TOOL 0 (flange),
;      otherwise the coordinates follow some other tool's TCP.
;   3. Turn the pendant speed override down to 20 percent for the first
;      run and keep a hand on the e-stop.
;   4. dryrun = 1 skips the valve signals.  Set it to 0 only when a
;      valve is actually wired to the output.
;
; ALL COMMENTS MUST STAY ASCII - see sugar_server.as header.
; =====================================================================

  dryrun = 1                 ; 1 = do not touch the valve output
  sig    = 1                  ; valve digital output number

  ACCURACY 3 ALWAYS

  SPEED 300 MM/S ALWAYS
  POINT st = SHIFT(org BY -78.03, -1.95, 30)
  LMOVE st
  POINT st = SHIFT(org BY -78.03, -1.95, 0)
  LMOVE st
  BREAK
  IF dryrun == 0 THEN
    SIGNAL 1
  END
  TWAIT 0.15
  SPEED 60 MM/S ALWAYS
  POINT st = SHIFT(org BY -71.63, -5.17, 0)
  LMOVE st
  POINT st = SHIFT(org BY -64.52, -6.05, 0)
  LMOVE st
  POINT st = SHIFT(org BY -58.54, -5.62, 0)
  LMOVE st
  SPEED 80 MM/S ALWAYS
  POINT st = SHIFT(org BY -46.68, -3.85, 0)
  LMOVE st
  POINT st = SHIFT(org BY -39.58, -2.71, 0)
  LMOVE st
  POINT st = SHIFT(org BY -32.46, -1.65, 0)
  LMOVE st
  POINT st = SHIFT(org BY -25.32, -0.75, 0)
  LMOVE st
  POINT st = SHIFT(org BY -18.17, 0.01, 0)
  LMOVE st
  POINT st = SHIFT(org BY -11.01, 0.70, 0)
  LMOVE st
  POINT st = SHIFT(org BY -3.85, 1.39, 0)
  LMOVE st
  POINT st = SHIFT(org BY 3.31, 2.07, 0)
  LMOVE st
  POINT st = SHIFT(org BY 10.48, 2.73, 0)
  LMOVE st
  POINT st = SHIFT(org BY 17.65, 3.37, 0)
  LMOVE st
  POINT st = SHIFT(org BY 24.82, 3.98, 0)
  LMOVE st
  POINT st = SHIFT(org BY 31.99, 4.56, 0)
  LMOVE st
  POINT st = SHIFT(org BY 39.16, 5.09, 0)
  LMOVE st
  POINT st = SHIFT(org BY 46.34, 5.55, 0)
  LMOVE st
  POINT st = SHIFT(org BY 53.53, 5.91, 0)
  LMOVE st
  POINT st = SHIFT(org BY 59.52, 6.05, 0)
  LMOVE st
  SPEED 60 MM/S ALWAYS
  POINT st = SHIFT(org BY 66.69, 5.60, 0)
  LMOVE st
  POINT st = SHIFT(org BY 73.51, 3.48, 0)
  LMOVE st
  SPEED 100 MM/S ALWAYS
  POINT st = SHIFT(org BY 78.03, -0.39, 0)
  LMOVE st
  BREAK
  IF dryrun == 0 THEN
    SIGNAL -1
  END
  TWAIT 0.1
  SPEED 300 MM/S ALWAYS
  LDEPART 30
  POINT st = SHIFT(org BY 0.00, 0.00, 30)
  LMOVE st
  BREAK
  PRINT "sugar_yi done"
.END

.PROGRAM Comment___ () ; Comments for IDE. Do not use.
	; @@@ PROJECT @@@
	; @@@ PROJECTNAME @@@
	; sugar_yi
	; @@@ HISTORY @@@
	; @@@ INSPECTION @@@
	; @@@ CONNECTION @@@
	; 
	; 
	; 
	; @@@ PROGRAM @@@
	; 0:sugar_yi:F
	; @@@ TRANS @@@
	; @@@ JOINTS @@@
	; @@@ REALS @@@
	; @@@ STRINGS @@@
	; @@@ INTEGER @@@
	; @@@ SIGNALS @@@
	; @@@ TOOLS @@@
	; @@@ BASE @@@
	; @@@ FRAME @@@
	; @@@ BOOL @@@
	; @@@ DEFAULTS @@@
	; BASE: NULL
	; TOOL: NULL
.END
