.PROGRAM sugar_frame()
; =====================================================================
; Frame check: 200x200 square around org
; Generated by motion2as.py from frame.pts.json
;
; 19 motions, 10 positions, estimated 17.8 s
; Offsets are relative to "org", the centre of the drawing area.
; X range -100.0 to +100.0 mm, Y range -100.0 to +100.0 mm
;
; BEFORE RUNNING
;   1. org must be taught (run org_teach) or this will not move sensibly.
;   2. Set TOOL correctly.  With no nozzle fitted use TOOL 0 (flange),
;      otherwise the coordinates follow some other tool's TCP.
;   3. Turn the pendant speed override down to 20 percent for the first
;      run and keep a hand on the e-stop.
;   4. dryrun = 1 skips the valve signals.  Set it to 0 only when a
;      valve is actually wired to the output.
;
; ALL COMMENTS MUST STAY ASCII - see sugar_server.as header.
; =====================================================================

  dryrun = 1                 ; 1 = do not touch the valve output
  sig    = 1                  ; valve digital output number

  ACCURACY 3 ALWAYS

  SPEED 300 MM/S ALWAYS
  POINT st = SHIFT(org BY 0.00, 0.00, 30)
  LMOVE st
  POINT st = SHIFT(org BY 0.00, 0.00, 0)
  LMOVE st
  BREAK
  IF dryrun == 0 THEN
    SIGNAL 1
  END
  TWAIT 0.15
  SPEED 60 MM/S ALWAYS
  POINT st = SHIFT(org BY 100.00, 0.00, 0)
  LMOVE st
  POINT st = SHIFT(org BY 100.00, 100.00, 0)
  LMOVE st
  POINT st = SHIFT(org BY -100.00, 100.00, 0)
  LMOVE st
  POINT st = SHIFT(org BY -100.00, -100.00, 0)
  LMOVE st
  POINT st = SHIFT(org BY 100.00, -100.00, 0)
  LMOVE st
  POINT st = SHIFT(org BY 100.00, 0.00, 0)
  LMOVE st
  POINT st = SHIFT(org BY 0.00, 0.00, 0)
  LMOVE st
  BREAK
  IF dryrun == 0 THEN
    SIGNAL -1
  END
  TWAIT 0.1
  SPEED 300 MM/S ALWAYS
  LDEPART 30
  POINT st = SHIFT(org BY 0.00, 0.00, 30)
  LMOVE st
  BREAK
  PRINT "sugar_frame done"
.END

.PROGRAM Comment___ () ; Comments for IDE. Do not use.
	; @@@ PROJECT @@@
	; @@@ PROJECTNAME @@@
	; sugar_frame
	; @@@ HISTORY @@@
	; @@@ INSPECTION @@@
	; @@@ CONNECTION @@@
	; 
	; 
	; 
	; @@@ PROGRAM @@@
	; 0:sugar_frame:F
	; @@@ TRANS @@@
	; @@@ JOINTS @@@
	; @@@ REALS @@@
	; @@@ STRINGS @@@
	; @@@ INTEGER @@@
	; @@@ SIGNALS @@@
	; @@@ TOOLS @@@
	; @@@ BASE @@@
	; @@@ FRAME @@@
	; @@@ BOOL @@@
	; @@@ DEFAULTS @@@
	; BASE: NULL
	; TOOL: NULL
.END
