.PROGRAM sugar_tai()
; =====================================================================
; Character test: tai (first char of Taiwan)
; Generated by motion2as.py from tai.pts.json
;
; 137 motions, 128 positions, estimated 8.8 s
; Offsets are relative to "org", the centre of the drawing area.
; X range -57.7 to +58.4 mm, Y range -77.0 to +79.3 mm
;
; BEFORE RUNNING
;   1. org must be taught (run org_teach) or this will not move sensibly.
;   2. Set TOOL correctly.  With no nozzle fitted use TOOL 0 (flange),
;      otherwise the coordinates follow some other tool's TCP.
;   3. Turn the pendant speed override down to 20 percent for the first
;      run and keep a hand on the e-stop.
;   4. dryrun = 1 skips the valve signals.  Set it to 0 only when a
;      valve is actually wired to the output.
;
; ALL COMMENTS MUST STAY ASCII - see sugar_server.as header.
; =====================================================================

  dryrun = 1                 ; 1 = do not touch the valve output
  sig    = 1                  ; valve digital output number

  ACCURACY 3 ALWAYS

  SPEED 300 MM/S ALWAYS
  POINT st = SHIFT(org BY -12.91, 79.30, 30)
  LMOVE st
  POINT st = SHIFT(org BY -12.91, 79.30, 0)
  LMOVE st
  BREAK
  IF dryrun == 0 THEN
    SIGNAL 1
  END
  TWAIT 0.15
  SPEED 60 MM/S ALWAYS
  POINT st = SHIFT(org BY -8.40, 75.37, 0)
  LMOVE st
  POINT st = SHIFT(org BY -4.61, 70.76, 0)
  LMOVE st
  POINT st = SHIFT(org BY -6.04, 65.13, 0)
  LMOVE st
  POINT st = SHIFT(org BY -8.17, 62.22, 0)
  LMOVE st
  POINT st = SHIFT(org BY -10.53, 59.49, 0)
  LMOVE st
  SPEED 80 MM/S ALWAYS
  POINT st = SHIFT(org BY -16.19, 53.27, 0)
  LMOVE st
  POINT st = SHIFT(org BY -21.10, 47.98, 0)
  LMOVE st
  POINT st = SHIFT(org BY -26.08, 42.76, 0)
  LMOVE st
  POINT st = SHIFT(org BY -31.09, 37.57, 0)
  LMOVE st
  POINT st = SHIFT(org BY -36.12, 32.39, 0)
  LMOVE st
  POINT st = SHIFT(org BY -41.13, 27.20, 0)
  LMOVE st
  POINT st = SHIFT(org BY -46.12, 22.00, 0)
  LMOVE st
  POINT st = SHIFT(org BY -51.06, 16.74, 0)
  LMOVE st
  SPEED 60 MM/S ALWAYS
  POINT st = SHIFT(org BY -53.48, 14.06, 0)
  LMOVE st
  POINT st = SHIFT(org BY -56.56, 10.37, 0)
  LMOVE st
  POINT st = SHIFT(org BY -57.69, 6.47, 0)
  LMOVE st
  POINT st = SHIFT(org BY -50.13, 4.56, 0)
  LMOVE st
  SPEED 80 MM/S ALWAYS
  POINT st = SHIFT(org BY -44.24, 5.75, 0)
  LMOVE st
  POINT st = SHIFT(org BY -37.26, 7.55, 0)
  LMOVE st
  POINT st = SHIFT(org BY -30.27, 9.37, 0)
  LMOVE st
  POINT st = SHIFT(org BY -23.26, 11.06, 0)
  LMOVE st
  POINT st = SHIFT(org BY -16.20, 12.53, 0)
  LMOVE st
  POINT st = SHIFT(org BY -9.11, 13.85, 0)
  LMOVE st
  POINT st = SHIFT(org BY -2.00, 15.09, 0)
  LMOVE st
  POINT st = SHIFT(org BY 5.12, 16.28, 0)
  LMOVE st
  SPEED 100 MM/S ALWAYS
  POINT st = SHIFT(org BY 8.68, 16.87, 0)
  LMOVE st
  POINT st = SHIFT(org BY 14.61, 17.82, 0)
  LMOVE st
  POINT st = SHIFT(org BY 20.55, 18.75, 0)
  LMOVE st
  SPEED 120 MM/S ALWAYS
  POINT st = SHIFT(org BY 25.31, 19.47, 0)
  LMOVE st
  POINT st = SHIFT(org BY 28.88, 19.97, 0)
  LMOVE st
  SPEED 100 MM/S ALWAYS
  POINT st = SHIFT(org BY 32.46, 20.38, 0)
  LMOVE st
  SPEED 120 MM/S ALWAYS
  POINT st = SHIFT(org BY 38.43, 20.00, 0)
  LMOVE st
  SPEED 140 MM/S ALWAYS
  POINT st = SHIFT(org BY 41.38, 17.97, 0)
  LMOVE st
  SPEED 220 MM/S ALWAYS
  POINT st = SHIFT(org BY 35.52, 22.99, 0)
  LMOVE st
  POINT st = SHIFT(org BY 31.48, 27.75, 0)
  LMOVE st
  POINT st = SHIFT(org BY 27.12, 35.29, 0)
  LMOVE st
  POINT st = SHIFT(org BY 24.59, 42.58, 0)
  LMOVE st
  SPEED 80 MM/S ALWAYS
  POINT st = SHIFT(org BY 28.21, 39.45, 0)
  LMOVE st
  POINT st = SHIFT(org BY 32.74, 35.54, 0)
  LMOVE st
  POINT st = SHIFT(org BY 37.27, 31.63, 0)
  LMOVE st
  POINT st = SHIFT(org BY 41.80, 27.71, 0)
  LMOVE st
  POINT st = SHIFT(org BY 46.30, 23.77, 0)
  LMOVE st
  SPEED 60 MM/S ALWAYS
  POINT st = SHIFT(org BY 48.98, 21.39, 0)
  LMOVE st
  POINT st = SHIFT(org BY 53.32, 17.27, 0)
  LMOVE st
  SPEED 80 MM/S ALWAYS
  POINT st = SHIFT(org BY 55.51, 13.03, 0)
  LMOVE st
  SPEED 120 MM/S ALWAYS
  POINT st = SHIFT(org BY 56.97, 9.75, 0)
  LMOVE st
  SPEED 200 MM/S ALWAYS
  POINT st = SHIFT(org BY 58.37, 6.45, 0)
  LMOVE st
  SPEED 220 MM/S ALWAYS
  POINT st = SHIFT(org BY 51.99, 2.23, 0)
  LMOVE st
  POINT st = SHIFT(org BY 46.61, -1.04, 0)
  LMOVE st
  POINT st = SHIFT(org BY 41.17, -4.09, 0)
  LMOVE st
  POINT st = SHIFT(org BY 35.67, -6.91, 0)
  LMOVE st
  POINT st = SHIFT(org BY 32.34, -8.50, 0)
  LMOVE st
  POINT st = SHIFT(org BY 26.75, -10.96, 0)
  LMOVE st
  POINT st = SHIFT(org BY 21.09, -13.20, 0)
  LMOVE st
  POINT st = SHIFT(org BY 15.38, -15.22, 0)
  LMOVE st
  POINT st = SHIFT(org BY 9.60, -17.02, 0)
  LMOVE st
  POINT st = SHIFT(org BY 6.11, -17.98, 0)
  LMOVE st
  POINT st = SHIFT(org BY -0.94, -19.68, 0)
  LMOVE st
  POINT st = SHIFT(org BY -8.07, -21.05, 0)
  LMOVE st
  POINT st = SHIFT(org BY -15.29, -22.11, 0)
  LMOVE st
  POINT st = SHIFT(org BY -22.60, -22.84, 0)
  LMOVE st
  POINT st = SHIFT(org BY -28.75, -23.20, 0)
  LMOVE st
  POINT st = SHIFT(org BY -34.96, -23.34, 0)
  LMOVE st
  POINT st = SHIFT(org BY -41.23, -23.26, 0)
  LMOVE st
  POINT st = SHIFT(org BY -47.56, -22.95, 0)
  LMOVE st
  POINT st = SHIFT(org BY -51.39, -22.66, 0)
  LMOVE st
  SPEED 60 MM/S ALWAYS
  POINT st = SHIFT(org BY -47.61, -25.58, 0)
  LMOVE st
  POINT st = SHIFT(org BY -43.96, -28.65, 0)
  LMOVE st
  SPEED 80 MM/S ALWAYS
  POINT st = SHIFT(org BY -42.48, -34.83, 0)
  LMOVE st
  POINT st = SHIFT(org BY -41.28, -40.68, 0)
  LMOVE st
  POINT st = SHIFT(org BY -40.08, -46.53, 0)
  LMOVE st
  POINT st = SHIFT(org BY -38.89, -52.38, 0)
  LMOVE st
  POINT st = SHIFT(org BY -37.70, -58.23, 0)
  LMOVE st
  POINT st = SHIFT(org BY -36.51, -64.08, 0)
  LMOVE st
  SPEED 100 MM/S ALWAYS
  POINT st = SHIFT(org BY -35.56, -68.76, 0)
  LMOVE st
  SPEED 120 MM/S ALWAYS
  POINT st = SHIFT(org BY -34.61, -73.44, 0)
  LMOVE st
  SPEED 160 MM/S ALWAYS
  POINT st = SHIFT(org BY -33.90, -76.96, 0)
  LMOVE st
  SPEED 220 MM/S ALWAYS
  POINT st = SHIFT(org BY -36.57, -70.89, 0)
  LMOVE st
  POINT st = SHIFT(org BY -38.51, -63.65, 0)
  LMOVE st
  POINT st = SHIFT(org BY -39.74, -56.35, 0)
  LMOVE st
  POINT st = SHIFT(org BY -40.27, -49.01, 0)
  LMOVE st
  POINT st = SHIFT(org BY -40.00, -40.39, 0)
  LMOVE st
  POINT st = SHIFT(org BY -39.00, -32.95, 0)
  LMOVE st
  POINT st = SHIFT(org BY -37.29, -25.47, 0)
  LMOVE st
  SPEED 60 MM/S ALWAYS
  POINT st = SHIFT(org BY -28.06, -26.28, 0)
  LMOVE st
  SPEED 80 MM/S ALWAYS
  POINT st = SHIFT(org BY -18.58, -25.00, 0)
  LMOVE st
  POINT st = SHIFT(org BY -11.50, -23.88, 0)
  LMOVE st
  POINT st = SHIFT(org BY -4.44, -22.61, 0)
  LMOVE st
  POINT st = SHIFT(org BY 2.60, -21.23, 0)
  LMOVE st
  POINT st = SHIFT(org BY 9.63, -19.81, 0)
  LMOVE st
  SPEED 60 MM/S ALWAYS
  POINT st = SHIFT(org BY 16.66, -18.42, 0)
  LMOVE st
  POINT st = SHIFT(org BY 22.56, -17.43, 0)
  LMOVE st
  POINT st = SHIFT(org BY 27.13, -18.53, 0)
  LMOVE st
  POINT st = SHIFT(org BY 31.37, -20.69, 0)
  LMOVE st
  POINT st = SHIFT(org BY 34.53, -25.29, 0)
  LMOVE st
  POINT st = SHIFT(org BY 34.12, -28.84, 0)
  LMOVE st
  POINT st = SHIFT(org BY 33.28, -32.32, 0)
  LMOVE st
  SPEED 80 MM/S ALWAYS
  POINT st = SHIFT(org BY 31.58, -38.05, 0)
  LMOVE st
  POINT st = SHIFT(org BY 30.07, -42.59, 0)
  LMOVE st
  SPEED 100 MM/S ALWAYS
  POINT st = SHIFT(org BY 28.46, -47.09, 0)
  LMOVE st
  POINT st = SHIFT(org BY 27.19, -50.44, 0)
  LMOVE st
  SPEED 80 MM/S ALWAYS
  POINT st = SHIFT(org BY 23.87, -56.74, 0)
  LMOVE st
  SPEED 120 MM/S ALWAYS
  POINT st = SHIFT(org BY 20.48, -57.42, 0)
  LMOVE st
  SPEED 220 MM/S ALWAYS
  POINT st = SHIFT(org BY 14.20, -61.64, 0)
  LMOVE st
  POINT st = SHIFT(org BY 8.81, -64.62, 0)
  LMOVE st
  POINT st = SHIFT(org BY 3.27, -67.12, 0)
  LMOVE st
  POINT st = SHIFT(org BY -2.41, -69.13, 0)
  LMOVE st
  POINT st = SHIFT(org BY -5.89, -70.11, 0)
  LMOVE st
  POINT st = SHIFT(org BY -13.00, -71.55, 0)
  LMOVE st
  POINT st = SHIFT(org BY -20.32, -72.28, 0)
  LMOVE st
  POINT st = SHIFT(org BY -27.85, -72.33, 0)
  LMOVE st
  SPEED 60 MM/S ALWAYS
  POINT st = SHIFT(org BY -30.51, -70.59, 0)
  LMOVE st
  POINT st = SHIFT(org BY -26.07, -69.09, 0)
  LMOVE st
  SPEED 80 MM/S ALWAYS
  POINT st = SHIFT(org BY -21.36, -68.37, 0)
  LMOVE st
  POINT st = SHIFT(org BY -15.45, -67.58, 0)
  LMOVE st
  POINT st = SHIFT(org BY -9.53, -66.85, 0)
  LMOVE st
  POINT st = SHIFT(org BY -3.61, -66.15, 0)
  LMOVE st
  POINT st = SHIFT(org BY 2.31, -65.48, 0)
  LMOVE st
  POINT st = SHIFT(org BY 8.24, -64.83, 0)
  LMOVE st
  POINT st = SHIFT(org BY 14.16, -64.20, 0)
  LMOVE st
  SPEED 60 MM/S ALWAYS
  POINT st = SHIFT(org BY 18.91, -63.75, 0)
  LMOVE st
  SPEED 80 MM/S ALWAYS
  POINT st = SHIFT(org BY 24.86, -63.49, 0)
  LMOVE st
  SPEED 100 MM/S ALWAYS
  POINT st = SHIFT(org BY 29.52, -64.47, 0)
  LMOVE st
  SPEED 140 MM/S ALWAYS
  POINT st = SHIFT(org BY 32.86, -65.75, 0)
  LMOVE st
  SPEED 180 MM/S ALWAYS
  POINT st = SHIFT(org BY 33.96, -66.21, 0)
  LMOVE st
  BREAK
  IF dryrun == 0 THEN
    SIGNAL -1
  END
  TWAIT 0.1
  SPEED 300 MM/S ALWAYS
  LDEPART 30
  POINT st = SHIFT(org BY 0.00, 0.00, 30)
  LMOVE st
  BREAK
  PRINT "sugar_tai done"
.END

.PROGRAM Comment___ () ; Comments for IDE. Do not use.
	; @@@ PROJECT @@@
	; @@@ PROJECTNAME @@@
	; sugar_tai
	; @@@ HISTORY @@@
	; @@@ INSPECTION @@@
	; @@@ CONNECTION @@@
	; 
	; 
	; 
	; @@@ PROGRAM @@@
	; 0:sugar_tai:F
	; @@@ TRANS @@@
	; @@@ JOINTS @@@
	; @@@ REALS @@@
	; @@@ STRINGS @@@
	; @@@ INTEGER @@@
	; @@@ SIGNALS @@@
	; @@@ TOOLS @@@
	; @@@ BASE @@@
	; @@@ FRAME @@@
	; @@@ BOOL @@@
	; @@@ DEFAULTS @@@
	; BASE: NULL
	; TOOL: NULL
.END
